# Site settings
title: Portfolio website Bartosz Kempa
email: bartosz.kempa@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio personal website
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username: jekyll

# GitHub metadata fallbacks to avoid API calls
github:
  repository_name: "0bart0.github.io"
  repository_url: "https://github.com/0bart0/0bart0.github.io"
  owner_name: "0bart0"
  owner_url: "https://github.com/0bart0"
  project_tagline: "Personal website"
  is_project_page: true
  zip_url: "https://github.com/0bart0/0bart0.github.io/archive/main.zip"
  tar_url: "https://github.com/0bart0/0bart0.github.io/archive/main.tar.gz"

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
plugins:
  - jekyll-feed

# Disable GitHub metadata to avoid API issues during build
repository: 0bart0/0bart0.github.io
