# Site settings
title: Your awesome title
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username: jekyll

# GitHub metadata fallbacks to avoid API calls
github:
  repository_name: "0bart0.github.io"
  repository_url: "https://github.com/0bart0/0bart0.github.io"
  owner_name: "0bart0"
  owner_url: "https://github.com/0bart0"
  project_tagline: "Personal website"
  is_project_page: true
  zip_url: "https://github.com/0bart0/0bart0.github.io/archive/main.zip"
  tar_url: "https://github.com/0bart0/0bart0.github.io/archive/main.tar.gz"

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
plugins:
  - jekyll-feed

# Disable GitHub metadata to avoid API issues during build
repository: 0bart0/0bart0.github.io